// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package authorization

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4258a2bdDecodeGithubComDeadlineTeamDtalksBotApiModelAuthorization(in *jlexer.Lexer, out *Authority) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "method":
			out.Method = string(in.String())
		case "description":
			out.Description = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4258a2bdEncodeGithubComDeadlineTeamDtalksBotApiModelAuthorization(out *jwriter.Writer, in Authority) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ID != "" {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	if in.Method != "" {
		const prefix string = ",\"method\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Method))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Description))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Authority) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4258a2bdEncodeGithubComDeadlineTeamDtalksBotApiModelAuthorization(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Authority) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4258a2bdEncodeGithubComDeadlineTeamDtalksBotApiModelAuthorization(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Authority) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4258a2bdDecodeGithubComDeadlineTeamDtalksBotApiModelAuthorization(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Authority) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4258a2bdDecodeGithubComDeadlineTeamDtalksBotApiModelAuthorization(l, v)
}
