// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package authorization

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4c1ffedcDecodeGithubComDeadlineTeamDtalksBotApiModelAuthorization(in *jlexer.Lexer, out *BaseUserStatus) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "icon":
			out.Icon = string(in.String())
		case "value":
			out.Value = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4c1ffedcEncodeGithubComDeadlineTeamDtalksBotApiModelAuthorization(out *jwriter.Writer, in BaseUserStatus) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ID != "" {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	if in.Icon != "" {
		const prefix string = ",\"icon\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Icon))
	}
	if in.Value != "" {
		const prefix string = ",\"value\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BaseUserStatus) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4c1ffedcEncodeGithubComDeadlineTeamDtalksBotApiModelAuthorization(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BaseUserStatus) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4c1ffedcEncodeGithubComDeadlineTeamDtalksBotApiModelAuthorization(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BaseUserStatus) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4c1ffedcDecodeGithubComDeadlineTeamDtalksBotApiModelAuthorization(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BaseUserStatus) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4c1ffedcDecodeGithubComDeadlineTeamDtalksBotApiModelAuthorization(l, v)
}
