// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	model "github.com/deadline-team/dtalks-bot-api/model"
	user "github.com/deadline-team/dtalks-bot-api/model/user"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	time "time"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3b86cc18DecodeGithubComDeadlineTeamDtalksBotApiModelScheduler(in *jlexer.Lexer, out *ScheduledTaskFilter) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "IDs":
			if in.IsNull() {
				in.Skip()
				out.IDs = nil
			} else {
				in.Delim('[')
				if out.IDs == nil {
					if !in.IsDelim(']') {
						out.IDs = make([]string, 0, 4)
					} else {
						out.IDs = []string{}
					}
				} else {
					out.IDs = (out.IDs)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.IDs = append(out.IDs, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "ConversationId":
			out.ConversationId = string(in.String())
		case "Resolved":
			out.Resolved = bool(in.Bool())
		case "Search":
			out.Search = string(in.String())
		case "OwnershipID":
			out.OwnershipID = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b86cc18EncodeGithubComDeadlineTeamDtalksBotApiModelScheduler(out *jwriter.Writer, in ScheduledTaskFilter) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"IDs\":"
		out.RawString(prefix[1:])
		if in.IDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.IDs {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"ConversationId\":"
		out.RawString(prefix)
		out.String(string(in.ConversationId))
	}
	{
		const prefix string = ",\"Resolved\":"
		out.RawString(prefix)
		out.Bool(bool(in.Resolved))
	}
	{
		const prefix string = ",\"Search\":"
		out.RawString(prefix)
		out.String(string(in.Search))
	}
	{
		const prefix string = ",\"OwnershipID\":"
		out.RawString(prefix)
		out.String(string(in.OwnershipID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ScheduledTaskFilter) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b86cc18EncodeGithubComDeadlineTeamDtalksBotApiModelScheduler(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ScheduledTaskFilter) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b86cc18EncodeGithubComDeadlineTeamDtalksBotApiModelScheduler(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ScheduledTaskFilter) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b86cc18DecodeGithubComDeadlineTeamDtalksBotApiModelScheduler(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ScheduledTaskFilter) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b86cc18DecodeGithubComDeadlineTeamDtalksBotApiModelScheduler(l, v)
}
func easyjson3b86cc18DecodeGithubComDeadlineTeamDtalksBotApiModelScheduler1(in *jlexer.Lexer, out *ScheduledTask) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "type":
			if in.IsNull() {
				in.Skip()
				out.Type = nil
			} else {
				in.Delim('[')
				if out.Type == nil {
					if !in.IsDelim(']') {
						out.Type = make([]ScheduledTaskDType, 0, 4)
					} else {
						out.Type = []ScheduledTaskDType{}
					}
				} else {
					out.Type = (out.Type)[:0]
				}
				for !in.IsDelim(']') {
					var v4 ScheduledTaskDType
					v4 = ScheduledTaskDType(in.String())
					out.Type = append(out.Type, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "createDate":
			if in.IsNull() {
				in.Skip()
				out.CreateDate = nil
			} else {
				if out.CreateDate == nil {
					out.CreateDate = new(time.Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.CreateDate).UnmarshalJSON(data))
				}
			}
		case "creator":
			if in.IsNull() {
				in.Skip()
				out.Creator = nil
			} else {
				if out.Creator == nil {
					out.Creator = new(user.User)
				}
				(*out.Creator).UnmarshalEasyJSON(in)
			}
		case "deadline":
			if in.IsNull() {
				in.Skip()
				out.Deadline = nil
			} else {
				if out.Deadline == nil {
					out.Deadline = new(time.Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.Deadline).UnmarshalJSON(data))
				}
			}
		case "object":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Object = make(model.Meta)
				} else {
					out.Object = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v5 interface{}
					if m, ok := v5.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v5.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v5 = in.Interface()
					}
					(out.Object)[key] = v5
					in.WantComma()
				}
				in.Delim('}')
			}
		case "meta":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Meta = make(model.Meta)
				} else {
					out.Meta = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v6 interface{}
					if m, ok := v6.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v6.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v6 = in.Interface()
					}
					(out.Meta)[key] = v6
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b86cc18EncodeGithubComDeadlineTeamDtalksBotApiModelScheduler1(out *jwriter.Writer, in ScheduledTask) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ID != "" {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"type\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.Type == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.Type {
				if v7 > 0 {
					out.RawByte(',')
				}
				out.String(string(v8))
			}
			out.RawByte(']')
		}
	}
	if in.CreateDate != nil {
		const prefix string = ",\"createDate\":"
		out.RawString(prefix)
		out.Raw((*in.CreateDate).MarshalJSON())
	}
	if in.Creator != nil {
		const prefix string = ",\"creator\":"
		out.RawString(prefix)
		(*in.Creator).MarshalEasyJSON(out)
	}
	if in.Deadline != nil {
		const prefix string = ",\"deadline\":"
		out.RawString(prefix)
		out.Raw((*in.Deadline).MarshalJSON())
	}
	if len(in.Object) != 0 {
		const prefix string = ",\"object\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v9First := true
			for v9Name, v9Value := range in.Object {
				if v9First {
					v9First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v9Name))
				out.RawByte(':')
				if m, ok := v9Value.(easyjson.Marshaler); ok {
					m.MarshalEasyJSON(out)
				} else if m, ok := v9Value.(json.Marshaler); ok {
					out.Raw(m.MarshalJSON())
				} else {
					out.Raw(json.Marshal(v9Value))
				}
			}
			out.RawByte('}')
		}
	}
	if len(in.Meta) != 0 {
		const prefix string = ",\"meta\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v10First := true
			for v10Name, v10Value := range in.Meta {
				if v10First {
					v10First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v10Name))
				out.RawByte(':')
				if m, ok := v10Value.(easyjson.Marshaler); ok {
					m.MarshalEasyJSON(out)
				} else if m, ok := v10Value.(json.Marshaler); ok {
					out.Raw(m.MarshalJSON())
				} else {
					out.Raw(json.Marshal(v10Value))
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ScheduledTask) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b86cc18EncodeGithubComDeadlineTeamDtalksBotApiModelScheduler1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ScheduledTask) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b86cc18EncodeGithubComDeadlineTeamDtalksBotApiModelScheduler1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ScheduledTask) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b86cc18DecodeGithubComDeadlineTeamDtalksBotApiModelScheduler1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ScheduledTask) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b86cc18DecodeGithubComDeadlineTeamDtalksBotApiModelScheduler1(l, v)
}
