// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package favorite

import (
	json "encoding/json"
	authorization "github.com/deadline-team/dtalks-bot-api/model/authorization"
	conversation "github.com/deadline-team/dtalks-bot-api/model/conversation"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson404e7428DecodeGithubComDeadlineTeamDtalksBotApiModelFavorite(in *jlexer.Lexer, out *Favorite) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "groupName":
			out.GroupName = string(in.String())
		case "owner":
			if in.IsNull() {
				in.Skip()
				out.Owner = nil
			} else {
				if out.Owner == nil {
					out.Owner = new(authorization.User)
				}
				(*out.Owner).UnmarshalEasyJSON(in)
			}
		case "conversations":
			if in.IsNull() {
				in.Skip()
				out.Conversations = nil
			} else {
				in.Delim('[')
				if out.Conversations == nil {
					if !in.IsDelim(']') {
						out.Conversations = make([]*conversation.Conversation, 0, 8)
					} else {
						out.Conversations = []*conversation.Conversation{}
					}
				} else {
					out.Conversations = (out.Conversations)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *conversation.Conversation
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(conversation.Conversation)
						}
						(*v1).UnmarshalEasyJSON(in)
					}
					out.Conversations = append(out.Conversations, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "order":
			out.Order = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson404e7428EncodeGithubComDeadlineTeamDtalksBotApiModelFavorite(out *jwriter.Writer, in Favorite) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ID != "" {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	if in.GroupName != "" {
		const prefix string = ",\"groupName\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.GroupName))
	}
	if in.Owner != nil {
		const prefix string = ",\"owner\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.Owner).MarshalEasyJSON(out)
	}
	if len(in.Conversations) != 0 {
		const prefix string = ",\"conversations\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v2, v3 := range in.Conversations {
				if v2 > 0 {
					out.RawByte(',')
				}
				if v3 == nil {
					out.RawString("null")
				} else {
					(*v3).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	if in.Order != 0 {
		const prefix string = ",\"order\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Order))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Favorite) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson404e7428EncodeGithubComDeadlineTeamDtalksBotApiModelFavorite(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Favorite) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson404e7428EncodeGithubComDeadlineTeamDtalksBotApiModelFavorite(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Favorite) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson404e7428DecodeGithubComDeadlineTeamDtalksBotApiModelFavorite(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Favorite) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson404e7428DecodeGithubComDeadlineTeamDtalksBotApiModelFavorite(l, v)
}
